title: Parley Chat Docs
description: Documentation for Parley.

url: "https://parley-chat.github.io"
baseurl: "/documentation"
permalink: pretty

theme: just-the-docs
color_scheme: dark

# Enable color mode switching
color_scheme_supports_light_dark: true
heading_anchors: true

callouts:
  note:
    title: Note
    color: blue

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      has_toc: false

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true