title: Parley Chat Docs
description: Documentation for Parley.

url: "https://docs.parley-chat.site"
baseurl: "/documentation"
permalink: pretty

theme: just-the-docs
color_scheme: dark
heading_anchors: true

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  caution:
    title: Caution
    color: red
  important:
    title: Important
    color: purple

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      has_toc: false

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true
